openapi: "3.0.0"
info:
  version: 0.0.1
  title: 'EPine'
tags:
  - name: Auth
paths:
  '/v1/auth/request':
    get:
      summary: 'Auth request'
      operationId: 'authRequest'
      description: 'Request URI for authorization'
      parameters:
      - in: header
        name: x-session-id
        schema:
          type: string
        required: true
        description: 'SessionId is returned after user subscribes via websockets'
      tags:
        - Auth
      responses:
        '200':
          description: 'URI'
          content:
            application/json:
              schema:
                type: object
                properties:
                  uri:
                    type: string
        '400':
          description: 'Bad request'
  '/v1/ton/auth/request':
    get:
      summary: 'TON Auth request'
      operationId: 'tonAuthRequest'
      description: 'Request URL for authorization'
      parameters:
      - in: header
        name: x-session-id
        schema:
          type: string
        required: true
        description: 'SessionId is returned after user subscribes via websockets'
      tags:
        - Auth
      responses:
        '200':
          description: 'URI'
          content:
            application/json:
              schema:
                type: object
                properties:
                  uri:
                    type: string
        '400':
          description: 'Bad request'
